services:
  backend:
    container_name: peoplelocation-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8899:8899"
    volumes:
        - ./backend/static:/app/static
        - ./backend/data:/app/data
        - ./weights/yolov8s.pt:/app/yolov8s.pt:ro
        - ./weights/osnet_x0_25_market1501.pt:/app/osnet_x0_25_market1501.pt:ro
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    container_name: peoplelocation-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
